# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Fuzzy Logic Studios
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Computer programmer, game developer, educator and content creator.  Game development is my jam, whether it
  be video games, board games or tabletop RPG's.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: B_Taylor_
github_username: brenttaylor 

# Build settings
#theme: minima
remote_theme: hydecorp/hydejack@v9.1.4
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

menu:
  - title: Youtube
    url: https://www.youtube.com/channel/UC4lODrEWBwfGlpDIaAeKV5Q
  - title: Blog
    url: /blog
  - title: Tabletop Gaming
    url: https://d100advocate.com


hydejack:
  no_mark_external: true
  no_drawer: true
  no_navbar: true
  no_search: true

clap_button: false
paginate: 10
paginate_path: 'blog/:num/'
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
